#!/bin/bash

# Real-time testing script for 9anime player extension

echo "🔧 9Anime Player - Real-Time Testing Setup"
echo "=========================================="
echo ""

# Check if Firefox is running
if pgrep -x "firefox" > /dev/null; then
    echo "✅ Firefox is running"
else
    echo "❌ Firefox is not running"
    echo "   Starting Firefox..."
    firefox "about:debugging#/runtime/this-firefox" &
    sleep 3
fi

echo ""
echo "📋 Real-Time Testing Steps:"
echo ""
echo "1️⃣  LOAD THE EXTENSION:"
echo "   • Go to: about:debugging#/runtime/this-firefox"
echo "   • Click 'Load Temporary Add-on'"
echo "   • Select: $(pwd)/manifest.json"
echo ""
echo "2️⃣  OPEN 9ANIME TEST PAGE:"
echo "   Opening test page in 3 seconds..."
sleep 3
firefox "https://9animetv.to/watch/demon-slayer-kimetsu-no-yaiba-47?ep=952" &
echo "   ✅ Test page opening..."
echo ""
echo "3️⃣  OPEN BROWSER CONSOLE:"
echo "   • Press F12 to open Developer Tools"
echo "   • Click 'Console' tab"
echo "   • Look for messages starting with: [9Anime Player]"
echo ""
echo "4️⃣  RUN DEBUG INSPECTOR:"
echo "   • Copy the contents of: $(pwd)/debug-inspector.js"
echo "   • Paste into console and press Enter"
echo "   • Examine the output to see page structure"
echo ""
echo "5️⃣  HOT RELOAD WORKFLOW:"
echo "   a) Edit content.js (or any file)"
echo "   b) Save the file (Ctrl+S)"
echo "   c) Go to about:debugging#/runtime/this-firefox"
echo "   d) Click 'Reload' next to the extension"
echo "   e) Refresh the 9anime page (F5)"
echo "   f) Check console for new logs"
echo ""
echo "📊 WHAT TO CHECK IN CONSOLE:"
echo ""
echo "✅ Extension loaded:"
echo "   [9Anime Player] Content script loaded"
echo ""
echo "✅ Video found:"
echo "   [9Anime Player] Video element found after X attempts!"
echo ""
echo "✅ Episode info extracted:"
echo "   [9Anime Player] Extracted info: {anime, episode, episodeId, genres}"
echo ""
echo "✅ Fullscreen activated:"
echo "   [9Anime Player] Fullscreen activated successfully!"
echo ""
echo "✅ Next button found:"
echo "   [9Anime Player] Navigation result: {nextUrl, isLast}"
echo ""
echo "🔍 DEBUGGING TIPS:"
echo ""
echo "• If video not found: Check iframe count in console"
echo "• If fullscreen fails: Click the page first (browser security)"
echo "• If next episode fails: Run debug inspector to find button structure"
echo "• Check all logs with: grep '[9Anime Player]' in console filter"
echo ""
echo "📝 QUICK CONSOLE COMMANDS:"
echo ""
echo "// Check for video"
echo "document.querySelector('video')"
echo ""
echo "// Check iframes"
echo "document.querySelectorAll('iframe').length"
echo ""
echo "// Find Next button"
echo "Array.from(document.querySelectorAll('a, button')).filter(el => el.textContent.toLowerCase().includes('next'))"
echo ""
echo "// Test fullscreen"
echo "document.documentElement.requestFullscreen()"
echo ""
echo "=========================================="
echo "🎬 Ready for testing! Good luck! 🚀"
